import { useState } from "react";
import { ArrowUpRight, Check, Flower2, Heart, Leaf, ShieldCheck, Sparkles, TreePine, UsersRound } from "lucide-react";

type Member = { name: string; role: string; responsibility: string; emotion: string; initials: string; color: string; position: string; status: string };

const members: Member[] = [
  { name: "Dad", role: "Parent", responsibility: "Medication pickup", emotion: "Calm", initials: "DA", color: "#D8925E", position: "left-[3%] top-[48%]", status: "Ready to help" },
  { name: "Mom", role: "Parent", responsibility: "Meal planning", emotion: "Happy", initials: "MO", color: "#D97E91", position: "left-[17%] top-[20%]", status: "Updated 8m ago" },
  { name: "Grandpa", role: "Care recipient", responsibility: "Morning check-in", emotion: "Tired", initials: "GP", color: "#8A7CB8", position: "left-[35%] top-[8%]", status: "Needs a check-in" },
  { name: "Grandma", role: "Care recipient", responsibility: "Thursday visit", emotion: "Worried", initials: "GM", color: "#B8795B", position: "right-[34%] top-[8%]", status: "Appointment Thursday" },
  { name: "Sister", role: "Coordinator", responsibility: "Family updates", emotion: "Focused", initials: "SI", color: "#4D946F", position: "right-[16%] top-[20%]", status: "Coordinating today" },
  { name: "Brother", role: "Driver", responsibility: "Hospital ride", emotion: "Ready", initials: "BR", color: "#5689AF", position: "right-[3%] top-[48%]", status: "Ride not confirmed" },
  { name: "Friend", role: "Support", responsibility: "Evening call", emotion: "Caring", initials: "FR", color: "#789965", position: "left-[18%] bottom-[8%]", status: "Available tonight" },
  { name: "Wife", role: "Partner", responsibility: "Comfort & notes", emotion: "Steady", initials: "WI", color: "#A1729F", position: "right-[18%] bottom-[8%]", status: "Last note yesterday" },
];

const emotionTone: Record<string, string> = { Calm: "#43815E", Happy: "#A46B34", Tired: "#665787", Worried: "#A25C50", Focused: "#43815E", Ready: "#4D7694", Caring: "#43815E", Steady: "#875C80" };

export default function FamilyCareTree() {
  const [active, setActive] = useState<Member>(members[3]);
  return <section aria-labelledby="family-tree-title" className="relative mt-7 overflow-hidden rounded-[32px] bg-[#e7f2e8] shadow-[0_20px_60px_rgba(42,78,53,.14)]">
    <style>{`@keyframes sceneIn { from { opacity:0; transform:scale(1.04); } to { opacity:1; transform:scale(1); } } @keyframes cardIn { from { opacity:0; transform:translateY(12px); } to { opacity:1; transform:translateY(0); } } @keyframes leafFloat { 0%,100% { transform:translateY(0) rotate(-8deg); } 50% { transform:translateY(-7px) rotate(8deg); } } .scene-photo { animation:sceneIn 1.1s ease-out both; } .scene-card { animation:cardIn .55s both cubic-bezier(.2,.8,.2,1); } .scene-leaf { animation:leafFloat 4s ease-in-out infinite; }`}</style>
    <div className="relative min-h-[700px] overflow-hidden sm:min-h-[650px] lg:min-h-[600px]"><img src="/assets/family-care-tree.jpg" alt="A large tree standing in a sunny green field" className="scene-photo absolute inset-0 h-full w-full object-cover object-center" /><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(8,53,76,.34)_0%,rgba(8,53,76,.02)_32%,rgba(22,77,39,.22)_65%,rgba(18,55,31,.56)_100%)]" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_44%,transparent_0%,transparent_30%,rgba(14,46,29,.20)_100%)]" />
      <div className="relative z-10 flex flex-col gap-5 px-5 py-6 sm:px-8 sm:py-8 lg:px-10"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div className="max-w-xl text-white"><div className="flex flex-wrap items-center gap-2 text-[10px] font-bold uppercase tracking-[0.2em] text-white/85"><TreePine className="h-3.5 w-3.5" /> Family care, growing together <span className="rounded-full border border-white/30 bg-white/15 px-2.5 py-1 tracking-[0.08em] backdrop-blur-sm">8 members · live context</span></div><h2 id="family-tree-title" className="mt-4 font-display text-[34px] font-semibold leading-[.98] tracking-[-0.05em] drop-shadow-[0_3px_16px_rgba(0,0,0,.22)] sm:text-[48px]">Care has roots.<br />Love has branches.</h2><p className="mt-4 max-w-md text-sm leading-6 text-white/85">A living view of the people, responsibilities, and emotions holding this family together.</p></div><div className="flex w-fit items-center gap-3 rounded-2xl border border-white/30 bg-[#123e32]/50 px-4 py-3 text-white shadow-lg backdrop-blur-md"><div className="flex -space-x-2">{members.slice(0, 4).map((member) => <span key={member.name} className="flex h-8 w-8 items-center justify-center rounded-full border-2 border-white/60 text-[9px] font-extrabold text-white" style={{ backgroundColor: member.color }}>{member.initials}</span>)}</div><div><p className="text-xs font-bold">Shared care circle</p><p className="mt-0.5 text-[10px] text-white/70">4 active today</p></div><ArrowUpRight className="h-4 w-4 text-white/70" /></div></div>
      <div className="pointer-events-none absolute inset-x-0 top-[27%] hidden h-[230px] lg:block"><div className="absolute left-1/2 top-1/2 h-40 w-40 -translate-x-1/2 -translate-y-1/2 rounded-full border border-white/35 bg-white/10 shadow-[0_0_0_18px_rgba(255,255,255,.08)] backdrop-blur-[1px]" /><div className="absolute left-1/2 top-1/2 flex h-16 w-16 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border border-white/70 bg-[#2f6b58]/85 text-white shadow-[0_8px_24px_rgba(0,0,0,.2)]"><Heart className="h-7 w-7" fill="currentColor" /></div></div>
      {members.map((member, index) => <button key={member.name} onMouseEnter={() => setActive(member)} onFocus={() => setActive(member)} onClick={() => setActive(member)} className={`scene-card absolute ${member.position} z-20 w-[155px] rounded-2xl border border-white/45 bg-white/86 p-3 text-left shadow-[0_12px_30px_rgba(12,49,28,.2)] backdrop-blur-md transition duration-200 hover:-translate-y-1 hover:bg-white hover:shadow-[0_18px_38px_rgba(12,49,28,.28)] focus:outline-none focus:ring-4 focus:ring-white/60 sm:w-[170px]`} style={{ borderLeft: `4px solid ${member.color}`, animationDelay: `${.55 + index * .07}s` }}><div className="flex items-center gap-2"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-[9px] font-extrabold text-white" style={{ backgroundColor: member.color }}>{member.initials}</span><span className="min-w-0"><span className="block truncate text-xs font-extrabold text-[#294335]">{member.name}</span><span className="block truncate text-[9px] text-[#79907E]">{member.role}</span></span><span className="ml-auto h-1.5 w-1.5 shrink-0 rounded-full bg-[#5FAD72]" /></div><div className="mt-2 flex items-center gap-1.5 border-t border-[#E5EFE5] pt-2"><Flower2 className="h-3.5 w-3.5 shrink-0" style={{ color: member.color }} /><span className="truncate text-[10px] font-bold text-[#55705C]">{member.responsibility}</span></div><span className="mt-1.5 inline-flex items-center gap-1 rounded-full bg-[#F4F8F3] px-2 py-0.5 text-[9px] font-bold" style={{ color: emotionTone[member.emotion] }}><Sparkles className="h-2.5 w-2.5" /> {member.emotion}</span></button>)}
      <div className="scene-leaf absolute bottom-[25%] left-[43%] text-white/65"><Leaf className="h-6 w-6 rotate-[-24deg]" fill="currentColor" /></div><div className="scene-leaf absolute bottom-[20%] left-[55%] text-white/55" style={{ animationDelay: "1.1s" }}><Leaf className="h-5 w-5 rotate-[26deg]" fill="currentColor" /></div>
      <div className="absolute bottom-5 left-5 right-5 z-30 flex flex-col gap-3 sm:left-8 sm:right-8 sm:flex-row sm:items-end sm:justify-between"><div className="rounded-2xl border border-white/30 bg-[#123e32]/58 px-4 py-3 text-white shadow-lg backdrop-blur-md"><div className="flex items-center gap-2 text-[9px] font-bold uppercase tracking-[0.16em] text-white/65"><span className="h-1.5 w-1.5 rounded-full bg-[#8BD39B]" /> Selected branch</div><p className="mt-1 text-sm font-bold">{active.name} is carrying {active.responsibility.toLowerCase()}</p><p className="mt-0.5 text-[11px] text-white/70">Feeling {active.emotion.toLowerCase()} · {active.status}</p></div><div className="flex items-center gap-2 text-[10px] font-bold text-white/75"><ShieldCheck className="h-4 w-4" /> Private to this care circle</div></div>
    </div>
      <div className="flex flex-col gap-4 border-t border-white/25 bg-[#173f31]/96 px-5 py-4 text-white sm:flex-row sm:items-center sm:justify-between sm:px-8"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-white/12"><UsersRound className="h-4 w-4" /></div><div><p className="text-xs font-bold">Selected: {active.name} · {active.emotion}</p><p className="mt-0.5 text-[10px] text-white/60">Select another person to see their responsibility and care signal.</p></div></div><button onClick={() => document.getElementById("handoff")?.scrollIntoView({ behavior: "smooth" })} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-white px-4 text-xs font-bold text-[#245640] shadow-sm hover:bg-[#F2FAF3]">Add a care update <ArrowUpRight className="h-3.5 w-3.5" /></button></div>
    </div>
  </section>;
}
